name: moonpmtiles-ci

on:
  push:
  pull_request:

jobs:
  core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hustcer/setup-moonbit@v1
        with:
          version: 0.1.20260819
      - run: moon fmt --check
      - run: moon check --deny-warn --target all
      - run: moon test --deny-warn --target all
