name: moonpmtiles-ci

on:
  push:
  pull_request:

jobs:
  core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: moonbitlang/setup@v0.1
      - run: moon fmt --check
      - run: moon check --deny-warn --target all
      - run: moon test --deny-warn --target all
